# Tmux - Dracula Theme

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g mouse on
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -sg escape-time 0

bind r source-file ~/.tmux.conf \; display "Reloaded!"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D
bind -n S-Left previous-window
bind -n S-Right next-window
bind c new-window -c "#{pane_current_path}"
bind x kill-pane

setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard"

set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-yank"

set -g status on
set -g status-interval 1
set -g status-position bottom
set -g status-justify left
set -g status-style "bg=#282a36,fg=#f8f8f2"

set -g status-left-length 100
set -g status-left "#[fg=#282a36,bg=#bd93f9,bold]  #S #[fg=#bd93f9,bg=#282a36,nobold]"

set -g status-right-length 100
set -g status-right "#[fg=#44475a,bg=#282a36]#[fg=#f8f8f2,bg=#44475a]  %H:%M #[fg=#bd93f9,bg=#44475a]#[fg=#282a36,bg=#bd93f9,bold]  %d-%b "

set -g window-status-format "#[fg=#44475a,bg=#282a36]#[fg=#f8f8f2,bg=#44475a] #I: #W #[fg=#44475a,bg=#282a36]"
set -g window-status-current-format "#[fg=#ff79c6,bg=#282a36]#[fg=#282a36,bg=#ff79c6,bold] #I: #W #[fg=#ff79c6,bg=#282a36]"
set -g window-status-separator ""

set -g pane-border-style "fg=#44475a"
set -g pane-active-border-style "fg=#bd93f9"
set -g message-style "fg=#8be9fd,bg=#44475a,bold"
setw -g mode-style "fg=#ff79c6,bg=#44475a,bold"
setw -g clock-mode-colour "#bd93f9"

run "~/.tmux/plugins/tpm/tpm"
